apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-deployment
  labels:
    app: php-apache
spec:
  # Keep 5 replicas by default
  replicas: 5
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8sproject:v1
        ports:
        - containerPort: 80
        # Set this to pull locally instead of from Dockerhub
        imagePullPolicy: IfNotPresent