apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  labels:
    app: php-apache
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer